swiftmailer:
    transport: gmail
    auth_mode: login
    port: 465
    encryption: ssl
    host: smtp.gmail.com
    username: 'dtstataouine@gmail.com'
    password: '123456789AAaa'
    spool: { type: 'memory' }