swiftmailer:
    transport: gmail
    auth_mode: login
    port: 465
    encryption: ssl
    host: smtp.gmail.com
    username: 'facturation.abdeljalil@gmail.com'
    password: '55256020'
    spool: { type: 'memory' }